sudo: true
language: java

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
    
 mvn sonar:sonar \
  -Dsonar.projectKey=IhoFenixMFS_museo.numismatica \
  -Dsonar.organization=ihofenixmfs-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=f66b71c09d4bffdadacb0ceb1ff53bbe4706a55d
